# -*- coding: utf-8 -*-
"""Gold .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJMbkXpRrQVey-Z4DIZvACsHIPjr659y
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

gold_data = pd.read_csv('/content/gld_price_data.csv')

gold_data.head()

gold_data.tail()

gold_data.shape

gold_data.info()

gold_data.isnull().sum()

gold_data.describe()

"""1 positive correlation
2 negative correlation

"""

correlation = gold_data.corr()

plt.figure(figsize = (8,8))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f',annot=True, annot_kws={'size':8}, cmap='Greens')

print(correlation['GLD'])

sns.distplot(gold_data['GLD'],color='red')

N = gold_data.drop(['Date','GLD'],axis=1)
M = gold_data['GLD']

print(N)

print(M)

N_train, N_test, M_train, M_test = train_test_split(N, M, test_size = 0.2, random_state=3)

regressor = RandomForestRegressor(n_estimators=100)

regressor.fit(N_train,M_train)

test_data_prediction = regressor.predict(N_test)

print(test_data_prediction)

error_score = metrics.r2_score(M_test, test_data_prediction)
print("R squared error : ", error_score)

N_test = list(N_test)

plt.plot(M_test, color='red', label = 'Actual Value')
plt.plot(test_data_prediction, color='yellow', label='Predicted Value')
plt.title('Actual Price vs Predicted Price')
plt.xlabel('Number of values')
plt.ylabel('GLD Price')
plt.legend()
plt.show()

